// mic_drop.js - 精準修正版 (再次推遲 +700ms，總計較原始版 +1400ms)
const songData = [
    { "time": 1600, "text": "Waiting for beat...", "type": "wait" },

    // --- 序幕：應援開始 ---
    { "time": 6100, "text": "김.남.준!", "type": "chant" },
    { "time": 7324, "text": "김.석.진!", "type": "chant" },
    { "time": 8749, "text": "민.윤.기!", "type": "chant" },
    { "time": 10150, "text": "정.호.석!", "type": "chant" },
    { "time": 11571, "text": "박.지.민!", "type": "chant" },
    { "time": 12941, "text": "김.태.형!", "type": "chant" },
    { "time": 14386, "text": "전.정.국!", "type": "chant" },
    { "time": 15759, "text": "B.T.S!", "type": "chant" },

    // --- 第二輪應援 ---
    { "time": 17216, "text": "김.남.준!", "type": "chant" },
    { "time": 18605, "text": "김.석.진!", "type": "chant" },
    { "time": 20017, "text": "민.윤.기!", "type": "chant" },
    { "time": 21425, "text": "정.호.석!", "type": "chant" },
    { "time": 22809, "text": "박.지.민!", "type": "chant" },
    { "time": 24204, "text": "김.태.형!", "type": "chant" },
    { "time": 25675, "text": "전.정.국!", "type": "chant" },
    { "time": 27034, "text": "B.T.S!", "type": "chant" },

    // --- 主歌區 (Sing 模式) ---
    { "time": 28600, "text": "scream!", "type": "scream" },
    { "time": 41289, "text": "bang bang", "type": "chant" },
    { "time": 43928, "text": "clap clap", "type": "chant" },
    { "time": 52015, "text": "bungee", "type": "chant" },
  
    // --- 主歌區 ---
    { "time": 53398, "text": "전진", "type": "chant" },
    { "time": 57463, "text": "Billboard", "type": "chant" },
    { "time": 58950, "text": "worldwide", "type": "chant" },
    { "time": 68358, "text": "I do it I do it", "type": "chant" },
    { "time": 69900, "text": "Sue it", "type": "chant" },
  // --- 🚨 預警 (提前 3 秒) ---
    { "time": 71100, "text": "⚠️ INCOMING! ⚠️", "type": "warning" },

    // --- 中段錄製點 ---
  
    { "time": 74860, "text": "(bag)-①", "type": "chant" },
    { "time": 76286, "text": "(bag)-②", "type": "chant" },
    { "time": 78370, "text": "(가득해)", "type": "chant" },
    { "time": 80454, "text": "(that)-①", "type": "chant" },
    { "time": 81906, "text": "(that)-②", "type": "chant" },
    { "time": 83983, "text": "(학을 떼)", "type": "chant" },
    { "time": 87203, "text": "(성공)", "type": "chant" },
    { "time": 90009, "text": "(봉송)", "type": "chant" },
    { "time": 92863, "text": "(숑숑)", "type": "chant" },

    { "time": 95715, "text": "scream!", "type": "scream" },
     // --- 後半段數據 ---
    { "time": 101918, "text": "MIC Drop-①", "type": "chant" },
    { "time": 103341, "text": "MIC Drop-②", "type": "chant" },
    { "time": 104886, "text": "발 발", "type": "chant" },
    { "time": 106246, "text": "말 말", "type": "chant" },
    { "time": 107672, "text": "scream!", "type": "scream" },
    { "time": 112650, "text": "MIC Drop-①", "type": "chant" },
    { "time": 114076, "text": "MIC Drop-②", "type": "chant" }, 
    { "time": 115502, "text": "발 발", "type": "chant" }, 
    { "time": 116928, "text": "말 말", "type": "chant" },
    { "time": 120283, "text": "(자)", "type": "chant" },
    { "time": 121696, "text": "(ah)", "type": "chant" },
    { "time": 125915, "text": "쌔 쌤통", "type": "chant" },
    { "time": 128509, "text": "행복", "type": "chant" },
    { "time": 129935, "text": "scream!", "type": "scream" },
    { "time": 139843, "text": "MIC Drop baam", "type": "chant" },
    { "time": 142271, "text": "(bag)-①", "type": "chant" },
    { "time": 143660, "text": "(bag)-②", "type": "chant" },
    { "time": 145775, "text": "(가득해)", "type": "chant" },
    { "time": 147881, "text": "(that)-①", "type": "chant" },
    { "time": 149289, "text": "(that)-②", "type": "chant" },
    { "time": 151410, "text": "(학을 떼)", "type": "chant" },
    { "time": 154617, "text": "(성공)", "type": "chant" },
    { "time": 157441, "text": "(봉송)", "type": "chant" },
    { "time": 160267, "text": "(숑숑)", "type": "chant" },
    { "time": 161693, "text": "scream!", "type": "scream" },
    { "time": 169314, "text": "MIC Drop-①", "type": "chant" },
    { "time": 170772, "text": "MIC Drop-②", "type": "chant" },
    { "time": 172387, "text": "발 발", "type": "chant" },
    { "time": 173651, "text": "말 말", "type": "chant" },
    { "time": 175077, "text": "scream!", "type": "scream" },
    { "time": 180655, "text": "MIC Drop-①", "type": "chant" },
    { "time": 182051, "text": "MIC Drop-②", "type": "chant" },
    { "time": 183586, "text": "발 발", "type": "chant" },
    { "time": 184987, "text": "말 말", "type": "chant" },
    { "time": 185787, "text": "scream!", "type": "scream" },
    { "time": 200952, "text": "마지막 인사야", "type": "sing" },
    { "time": 206479, "text": "사과도 하지 마", "type": "sing" },
    { "time": 212180, "text": "마지막 인사야", "type": "sing" },
    { "time": 217808, "text": "사과도 하지 마", "type": "sing" },
    { "
